CREATE TABLE ORDERS (ID LONG PRIMARY KEY AUTO_INCREMENT, CUSTOMER_ID LONG, ORDER_DATE DATE, PRICE DOUBLE) ;

CREATE TABLE REWARDS_CONFIGURATION (ID INT PRIMARY KEY AUTO_INCREMENT, PRICE DOUBLE, REWARDS DOUBLE) ;